services:
  nextcloud:
    build:
      context: nextcloud
      dockerfile: Dockerfile.28
    container_name: nextcloud
    ports:
    - "8080:80"
    volumes:
    - nextcloud_data:/var/www/html
    - ../launch.json:/var/www/html/.vscode/launch.json
    - ../files_external_ethswarm:/var/www/html/custom_apps/files_external_ethswarm
    depends_on:
    - db
    environment:
    - MYSQL_PASSWORD=nextcloud_password
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db
    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=admin

  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
    - MYSQL_HOST=db
    - MYSQL_ROOT_PASSWORD=root_password
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=nextcloud_password
    volumes:
    - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
    - "8081:8080"

volumes:
  nextcloud_data:
  db_data: